name: DevOps CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: pytest test_app.py -v

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

       - name: Build and push Docker image
         run: |
          SHORT_SHA=$(git rev-parse --short HEAD)
          DOCKER_USER=Ya105
          docker build -t $DOCKER_USER/se-web-app:latest .
          docker tag $DOCKER_USER/se-web-app:latest $DOCKER_USER/se-web-app:$SHORT_SHA
          docker push $DOCKER_USER/se-web-app:latest
          docker push $DOCKER_USER/se-web-app:$SHORT_SHA
